- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install {{web}}
  apt:
    name: "{{web}}"
    state: present

- name: copy index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html

